[global]
   workgroup = WORKGROUP
   server string = Servidor Facturas
   netbios name = FACTURAS-SRV
   security = user
   map to guest = Bad User
   dns proxy = no
   log level = 1
   max log size = 1000
   interfaces = 192.168.10.0/24 lo
   bind interfaces only = yes
   hosts allow = 192.168.10. 127.
   hosts deny = ALL

[Facturas]
   comment = Carpeta de Facturas Escaneadas
   path = /srv/facturas/escaneadas
   browsable = yes
   writable = yes
   guest ok = yes
   guest account = nobody
   read only = no
   create mask = 0777
   directory mask = 0777
   force create mode = 0666
   force directory mode = 0777
